/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.matthewlemon.datamaps.gui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lemon
 */
public class CreateFromCSVDialog extends javax.swing.JDialog {

	private File choosenFile;

	public File getChoosenFile() {
		return choosenFile;
	}

	public String getGivenDatamapName() {
		return givenDatamapName;
	}
	private String givenDatamapName;

	/**
	 * Creates new form AddNewDatamap
	 */
	public CreateFromCSVDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        addDatamapPanel = new javax.swing.JPanel();
        givenDatamapNameLabel = new javax.swing.JLabel();
        selectedPathTextLabel = new javax.swing.JLabel();
        selectedFile = new javax.swing.JLabel();
        selectCSVBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        givenDatamapNameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Datamap from CSV");
        setName(""); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout());

        addDatamapPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datamap Details"));
        addDatamapPanel.setName("Add New Datamap"); // NOI18N
        java.awt.GridBagLayout addDatamapPanelLayout = new java.awt.GridBagLayout();
        addDatamapPanelLayout.columnWidths = new int[] {0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0};
        addDatamapPanelLayout.rowHeights = new int[] {0, 5, 0, 5, 0};
        addDatamapPanel.setLayout(addDatamapPanelLayout);

        givenDatamapNameLabel.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        addDatamapPanel.add(givenDatamapNameLabel, gridBagConstraints);

        selectedPathTextLabel.setText("GIVEN NAME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addDatamapPanel.add(selectedPathTextLabel, gridBagConstraints);

        selectedFile.setText("Selected File:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        addDatamapPanel.add(selectedFile, gridBagConstraints);

        selectCSVBtn.setText("Select CSV");
        selectCSVBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCSVBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        addDatamapPanel.add(selectCSVBtn, gridBagConstraints);

        okBtn.setText("OK");
        okBtn.setEnabled(false);
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        addDatamapPanel.add(okBtn, gridBagConstraints);

        givenDatamapNameField.setColumns(4);
        givenDatamapNameField.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        addDatamapPanel.add(givenDatamapNameField, gridBagConstraints);

        getContentPane().add(addDatamapPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectCSVBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCSVBtnActionPerformed
		if (givenDatamapNameField.getText().isBlank()) {
			JOptionPane.showMessageDialog(this, "Please provide a datamap name", "Error: Please provide a name", JOptionPane.ERROR_MESSAGE);
			return;
		}
		givenDatamapName = givenDatamapNameField.getText();
		JFileChooser fileChooser = new JFileChooser();
		FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV files", "csv");
		fileChooser.setFileFilter(filter);
		int returnValue = fileChooser.showDialog(addDatamapPanel, "Select CSV File");
		choosenFile = fileChooser.getSelectedFile();
		selectedPathTextLabel.setText(choosenFile.getAbsolutePath());
		okBtn.setEnabled(true);
		okBtn.requestFocus();
    }//GEN-LAST:event_selectCSVBtnActionPerformed


    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
		this.setVisible(false);
    }//GEN-LAST:event_okBtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CreateFromCSVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CreateFromCSVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CreateFromCSVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CreateFromCSVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				CreateFromCSVDialog dialog = new CreateFromCSVDialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addDatamapPanel;
    private javax.swing.JTextField givenDatamapNameField;
    private javax.swing.JLabel givenDatamapNameLabel;
    private javax.swing.JButton okBtn;
    private javax.swing.JButton selectCSVBtn;
    private javax.swing.JLabel selectedFile;
    private javax.swing.JLabel selectedPathTextLabel;
    // End of variables declaration//GEN-END:variables
}
