/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.matthewlemon.datamaps.gui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lemon
 */
public class CreateFromCSVDialog extends javax.swing.JDialog {

	private File choosenFile;

	public File getChoosenFile() {
		return choosenFile;
	}

	public String getGivenDatamapName() {
		return givenDatamapName;
	}
	private String givenDatamapName;

	/**
	 * Creates new form AddNewDatamap
	 */
	public CreateFromCSVDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDatamapPanel = new javax.swing.JPanel();
        givenDatamapNameLabel = new javax.swing.JLabel();
        givenDatamapNameField = new javax.swing.JTextField();
        selectCSVBtn = new javax.swing.JButton();
        selectedFile = new javax.swing.JLabel();
        selectedPathTextLabel = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Datamap from CSV");
        setName(""); // NOI18N

        addDatamapPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Datamap Details"));
        addDatamapPanel.setName("Add New Datamap"); // NOI18N

        givenDatamapNameLabel.setText("Name:");

        selectCSVBtn.setText("Select CSV");
        selectCSVBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCSVBtnActionPerformed(evt);
            }
        });

        selectedFile.setText("Selected File:");

        okBtn.setText("OK");
        okBtn.setEnabled(false);
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDatamapPanelLayout = new javax.swing.GroupLayout(addDatamapPanel);
        addDatamapPanel.setLayout(addDatamapPanelLayout);
        addDatamapPanelLayout.setHorizontalGroup(
            addDatamapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDatamapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addDatamapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDatamapPanelLayout.createSequentialGroup()
                        .addGroup(addDatamapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(givenDatamapNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(selectedFile, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addDatamapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(givenDatamapNameField)
                            .addComponent(selectedPathTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDatamapPanelLayout.createSequentialGroup()
                        .addGap(0, 331, Short.MAX_VALUE)
                        .addComponent(selectCSVBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okBtn)))
                .addContainerGap())
        );
        addDatamapPanelLayout.setVerticalGroup(
            addDatamapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDatamapPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addDatamapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(givenDatamapNameLabel)
                    .addComponent(givenDatamapNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDatamapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedFile)
                    .addComponent(selectedPathTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDatamapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectCSVBtn)
                    .addComponent(okBtn))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addDatamapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addDatamapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectCSVBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCSVBtnActionPerformed
		if (givenDatamapNameField.getText().isBlank()) {
			JOptionPane.showMessageDialog(this, "Please provide a datamap name", "Error: Please provide a name", JOptionPane.ERROR_MESSAGE);
			return;
		}
		givenDatamapName = givenDatamapNameField.getText();
		JFileChooser fileChooser = new JFileChooser();
		FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV files", "csv");
		fileChooser.setFileFilter(filter);
		int returnValue = fileChooser.showDialog(addDatamapPanel, "Select CSV File");
		choosenFile = fileChooser.getSelectedFile();
		selectedPathTextLabel.setText(choosenFile.getAbsolutePath());
		okBtn.setEnabled(true);
		okBtn.requestFocus();
    }//GEN-LAST:event_selectCSVBtnActionPerformed


    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
		this.setVisible(false);
    }//GEN-LAST:event_okBtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CreateFromCSVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CreateFromCSVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CreateFromCSVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CreateFromCSVDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				CreateFromCSVDialog dialog = new CreateFromCSVDialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addDatamapPanel;
    private javax.swing.JTextField givenDatamapNameField;
    private javax.swing.JLabel givenDatamapNameLabel;
    private javax.swing.JButton okBtn;
    private javax.swing.JButton selectCSVBtn;
    private javax.swing.JLabel selectedFile;
    private javax.swing.JLabel selectedPathTextLabel;
    // End of variables declaration//GEN-END:variables
}
