package com.matthewlemon.datamaps.gui;

import com.matthewlemon.datamaps.core.Context;
import com.matthewlemon.datamaps.core.entities.CSVFile;
import com.matthewlemon.datamaps.core.entities.Datamap;
import com.matthewlemon.datamaps.core.entities.DatamapLine;
import com.matthewlemon.datamaps.core.exceptions.DatamapNotFoundException;
import com.matthewlemon.datamaps.core.exceptions.DuplicateDatamapException;
import com.matthewlemon.datamaps.core.gateways.InMemoryDatamapGateway;
import com.matthewlemon.datamaps.core.usecases.CreateableDatamapUseCase;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lemon
 */
public class Home extends javax.swing.JFrame {

	private final CreateableDatamapUseCase useCase;
	private final DefaultTableModel datamapTableModel;
	private final DefaultTableModel datamapLineTableModel;

	public Home() {
		Context.datamapGateway = new InMemoryDatamapGateway();
		useCase = new CreateableDatamapUseCase();

		String[] newDatamapColNames = {"Datamap", "Status"};
		String[] datamapLineColNames = {"Key", "Sheet", "Cell Reference"};

		datamapTableModel = new DefaultTableModel(newDatamapColNames, 0) {
			@Override
			public boolean isCellEditable(int i, int i1) {
				return false;
			}
		};
		datamapLineTableModel = new DefaultTableModel(datamapLineColNames, 0);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datamapAdd = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datamapTable = new javax.swing.JTable();
        datamapData = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        datamapLineTable = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        addDatamapBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datamaps - Home");
        setBackground(new java.awt.Color(255, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        datamapAdd.setBorder(javax.swing.BorderFactory.createTitledBorder("Datamaps"));

        datamapTable.setModel(datamapTableModel);
        datamapTable.setShowGrid(true);
        datamapTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datamapTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(datamapTable);

        javax.swing.GroupLayout datamapAddLayout = new javax.swing.GroupLayout(datamapAdd);
        datamapAdd.setLayout(datamapAddLayout);
        datamapAddLayout.setHorizontalGroup(
            datamapAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datamapAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                .addContainerGap())
        );
        datamapAddLayout.setVerticalGroup(
            datamapAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datamapAddLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(datamapAdd);

        datamapData.setBorder(javax.swing.BorderFactory.createTitledBorder("Datamap Data"));

        datamapLineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        datamapLineTable.setName(""); // NOI18N
        jScrollPane2.setViewportView(datamapLineTable);

        javax.swing.GroupLayout datamapDataLayout = new javax.swing.GroupLayout(datamapData);
        datamapData.setLayout(datamapDataLayout);
        datamapDataLayout.setHorizontalGroup(
            datamapDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datamapDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                .addContainerGap())
        );
        datamapDataLayout.setVerticalGroup(
            datamapDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datamapDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(datamapData);

        addDatamapBtn.setText("Add");
        addDatamapBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDatamapBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap(849, Short.MAX_VALUE)
                .addComponent(addDatamapBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addDatamapBtn)
                .addContainerGap())
        );

        getContentPane().add(buttonPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void addDatamapBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDatamapBtnMouseClicked

			CreateFromCSVDialog newDatamapDialog = new CreateFromCSVDialog(this, rootPaneCheckingEnabled);
			Datamap datamap = null;
			newDatamapDialog.setLocationRelativeTo(this);
			newDatamapDialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
			newDatamapDialog.setVisible(true);
			String datamapName = newDatamapDialog.getGivenDatamapName();
			File csvFile = newDatamapDialog.getChoosenFile();
			try {
				datamap = useCase.createDatamap(datamapName);
				String dmName = datamap.getName();
				Object[] data = {dmName, "NA"};
				datamapTableModel.addRow(data);
				useCase.addCSVDataToDatamap(datamapName, new CSVFile(csvFile));
			} catch (DatamapNotFoundException | DuplicateDatamapException ex) {
				Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
			}
        }//GEN-LAST:event_addDatamapBtnMouseClicked

    private void datamapTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datamapTableMouseClicked
		int row = datamapTable.rowAtPoint(evt.getPoint());
		int col = datamapTable.columnAtPoint(evt.getPoint());
		String datamapName = (String) datamapTable.getValueAt(row, col);
		if (datamapLineTableModel.getRowCount() > 0) {
			for (int i = datamapLineTableModel.getRowCount() - 1; i>-1; i--) {
				datamapLineTableModel.removeRow(i);
			}
		}
		try {
			Datamap datamap = useCase.getDatamap(datamapName);
			for (DatamapLine line : useCase.getDatamap(datamapName).getDatamapLines()) {
				String[] rowData = {line.getKey(), line.getSheetName(), line.getCellRef()};
				System.out.println("Getting: " + line.getKey());
				datamapLineTableModel.addRow(rowData);
			}
			datamapLineTable.setModel(datamapLineTableModel);

		} catch (DatamapNotFoundException ex) {
			Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
		}

    }//GEN-LAST:event_datamapTableMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Home home = new Home();
				home.setLocationRelativeTo(null);
				home.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDatamapBtn;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel datamapAdd;
    private javax.swing.JPanel datamapData;
    private javax.swing.JTable datamapLineTable;
    private javax.swing.JTable datamapTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
